calculator:
  additionServiceUrl: http://localhost:8070/api/addition/calculate
  subtractionServiceUrl: http://localhost:8071/api/subtraction/calculate

server:
  port: 8080
spring:
  application:
    name: calculator-service
